/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author MSI
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new Calculator
     */
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void EnterNumbers(String q)
    {
        String Nums = txtResult.getText() + q;
        txtResult.setText(Nums);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCE = new javax.swing.JButton();
        btnBs = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnDigit7 = new javax.swing.JButton();
        btnDigit8 = new javax.swing.JButton();
        btnDigit9 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDigit4 = new javax.swing.JButton();
        btnDigit5 = new javax.swing.JButton();
        btnDigit6 = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnDigit1 = new javax.swing.JButton();
        btnDigit2 = new javax.swing.JButton();
        btnDigit3 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDigit0 = new javax.swing.JButton();
        btnDecimal = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 20, 30));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("CALCULATOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 30));

        btnCE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        getContentPane().add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 50));

        btnBs.setFont(new java.awt.Font("Wingdings", 0, 12)); // NOI18N
        btnBs.setText("⌫");
        btnBs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBs, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 50, 50));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setText("C");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, 50));

        btnPlusMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPlusMinus.setText("+-");
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 50, 50));

        btnDigit7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit7.setText("7");
        btnDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 50));

        btnDigit8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit8.setText("8");
        btnDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 50, 50));

        btnDigit9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit9.setText("9");
        btnDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 50, 50));

        btnAdd.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 50, 50));

        btnDigit4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit4.setText("4");
        btnDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, 50));

        btnDigit5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit5.setText("5");
        btnDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 50, 50));

        btnDigit6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit6.setText("6");
        btnDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 50, 50));

        btnSubtract.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnSubtract.setText("-");
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 50, 50));

        btnDigit1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit1.setText("1");
        btnDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 50, 50));

        btnDigit2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit2.setText("2");
        btnDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 50, 50));

        btnDigit3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit3.setText("3");
        btnDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 50, 50));

        btnMultiply.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 50, 50));

        btnDigit0.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDigit0.setText("0");
        btnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDigit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 50, 50));

        btnDecimal.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDecimal.setText(".");
        btnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalActionPerformed(evt);
            }
        });
        getContentPane().add(btnDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 50, 50));

        btnEqual.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(btnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 50, 50));

        btnDivide.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 50, 50));

        txtResult.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        getContentPane().add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit4ActionPerformed
        EnterNumbers("4");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit4ActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        NumEnter1 = Double.parseDouble(txtResult.getText());
        txtResult.setText("");
        op = "*";
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        NumEnter1 = Double.parseDouble(txtResult.getText());
        txtResult.setText("");
        op = "/";
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit7ActionPerformed
        EnterNumbers("7");      // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit7ActionPerformed

    private void btnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit8ActionPerformed
        EnterNumbers("8");// TODO add your handling code here:
    }//GEN-LAST:event_btnDigit8ActionPerformed

    private void btnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit9ActionPerformed
        EnterNumbers("9");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit9ActionPerformed

    private void btnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit5ActionPerformed
        EnterNumbers("5");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit5ActionPerformed

    private void btnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit6ActionPerformed
        EnterNumbers("6");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit6ActionPerformed

    private void btnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit1ActionPerformed
        EnterNumbers("1");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit1ActionPerformed

    private void btnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit2ActionPerformed
        EnterNumbers("2");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit2ActionPerformed

    private void btnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit3ActionPerformed
        EnterNumbers("3");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit3ActionPerformed

    private void btnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit0ActionPerformed
        EnterNumbers("0");        // TODO add your handling code here:
    }//GEN-LAST:event_btnDigit0ActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        NumEnter1 = Double.parseDouble(txtResult.getText());
        txtResult.setText("");
        op = "-";
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        NumEnter1 = Double.parseDouble(txtResult.getText());
        txtResult.setText("");
        op = "+";
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        txtResult.setText("");
        
        String Fn, Sn;
        
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn = "";
        Sn = "";
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        double nums = Double.parseDouble(String.valueOf(txtResult.getText()));
        nums = nums * (-1);
        txtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void btnBsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBsActionPerformed
        String backSp = null;
        
        if (txtResult.getText().length() > 0)
        {
            StringBuilder sb = new StringBuilder(txtResult.getText());
            sb.deleteCharAt(txtResult.getText().length() - 1);
            backSp = sb.toString();
            txtResult.setText(backSp);
        }
    }//GEN-LAST:event_btnBsActionPerformed

    private void btnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalActionPerformed
        if (! txtResult.getText().contains("."))
        {
            txtResult.setText(txtResult.getText() + btnDecimal.getText());
        }
    }//GEN-LAST:event_btnDecimalActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        NumEnter2 = Double.parseDouble(txtResult.getText());
        
        if (op == "+"){
            Result = NumEnter1 + NumEnter2;
            txtResult.setText(String.valueOf(Result));
        } else if (op == "-"){
            Result = NumEnter1 - NumEnter2;
            txtResult.setText(String.valueOf(Result));
        } else if (op == "*"){
            Result = NumEnter1 * NumEnter2;
            txtResult.setText(String.valueOf(Result));
        } else if (op == "/"){
            Result = NumEnter1 / NumEnter2;
            txtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBs;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDecimal;
    private javax.swing.JButton btnDigit0;
    private javax.swing.JButton btnDigit1;
    private javax.swing.JButton btnDigit2;
    private javax.swing.JButton btnDigit3;
    private javax.swing.JButton btnDigit4;
    private javax.swing.JButton btnDigit5;
    private javax.swing.JButton btnDigit6;
    private javax.swing.JButton btnDigit7;
    private javax.swing.JButton btnDigit8;
    private javax.swing.JButton btnDigit9;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
